function eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet(){var Y='',V=' top: -1000px;',tb='" for "gwt:onLoadErrorFn"',rb='" for "gwt:onPropertyErrorFn"',cb='");',ub='#',Xb='.cache.js',wb='/',Cb='//',Qb='14E352E53C66FC79F16D2EF9BF1A8FF8',Rb='16E230ACDFD1758DF36C07BA13569AD3',Sb='3B38A1B972459FD9920479304F1EFF94',Tb='6BE37A8B144C4BB63CE8F3913A60C613',Ub='883E7702B0276F37691B18C557C5E6CF',Wb=':',lb='::',_b=':moduleBase',X='<!doctype html>',Z='<html><head><\/head><body><\/body><\/html>',ob='=',vb='?',qb='Bad handler "',W='CSS1Compat',ab='Chrome',_='DOMContentLoaded',Q='DUMMY',Vb='E1160C0B49C972E3FFDE3B4109063460',$b='__gwtDevModeHook:eu.etaxonomy.cdm.remote.webapp.view.widgetset.AppWidgetSet',Bb='base',zb='baseUrl',L='begin',R='body',K='bootstrap',yb='clear.cache.gif',nb='content',Zb='end',O='eu.etaxonomy.cdm.remote.webapp.view.widgetset.AppWidgetSet',Pb='eu.etaxonomy.cdm.remote.webapp.view.widgetset.AppWidgetSet.devmode.js',Ab='eu.etaxonomy.cdm.remote.webapp.view.widgetset.AppWidgetSet.nocache.js',kb='eu.etaxonomy.cdm.remote.webapp.view.widgetset.AppWidgetSet::',bb='eval("',Lb='gecko',Mb='gecko1_8',M='gwt.codesvr.eu.etaxonomy.cdm.remote.webapp.view.widgetset.AppWidgetSet=',N='gwt.codesvr=',sb='gwt:onLoadErrorFn',pb='gwt:onPropertyErrorFn',mb='gwt:property',hb='head',Kb='ie6',Jb='ie8',Ib='ie9',S='iframe',xb='img',eb='javascript',T='javascript:""',Yb='loadExternalRefs',ib='meta',gb='moduleRequested',fb='moduleStartup',Hb='msie',jb='name',Eb='opera',U='position:absolute; width:0; height:0; border:none; left: -1000px;',Gb='safari',db='script',Ob='selectingPermutation',P='startup',$='undefined',Nb='unknown',Db='user.agent',Fb='webkit';var o=window;var p=document;r(K,L);function q(){var a=o.location.search;return a.indexOf(M)!=-1||a.indexOf(N)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:O,sessionId:o.__gwtStatsSessionId,subSystem:P,evtGroup:a,millis:(new Date).getTime(),type:b})}}
eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.__sendStats=r;eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.__moduleName=O;eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.__errFn=null;eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.__moduleBase=Q;eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.__softPermutationId=0;eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.__computePropValue=null;eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.__getPropMap=null;eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.__gwtInstallCode=function(){};eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[O]={moduleName:O};var v;function w(){y();return v}
function x(){y();return v.getElementsByTagName(R)[0]}
function y(){if(v){return}var a=p.createElement(S);a.src=T;a.id=O;a.style.cssText=U+V;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==W?X:Y;v.write(b+Z);v.close()}
function z(k){function l(a){function b(){if(typeof p.readyState==$){return typeof p.body!=$&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(_,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(_,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=x();var f=w();var g;if(navigator.userAgent.indexOf(ab)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(bb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(cb));g=f.createElement(db);g.language=eb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(db);g.language=eb;g.text=c[i];e.appendChild(g);d(e,g)}}}
eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.onScriptDownloaded=function(a){l(function(){m(a)})};r(fb,gb);var n=p.createElement(db);n.src=k;p.getElementsByTagName(hb)[0].appendChild(n)}
eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.__startLoadingFragment=function(a){return C(a)};eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.__installRunAsyncCode=function(a){var b=x();var c=w().createElement(db);c.language=eb;c.text=a;b.appendChild(c);b.removeChild(c)};function A(){var c={};var d;var e;var f=p.getElementsByTagName(ib);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(jb),k;if(j){j=j.replace(kb,Y);if(j.indexOf(lb)>=0){continue}if(j==mb){k=i.getAttribute(nb);if(k){var l,m=k.indexOf(ob);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=Y}c[j]=l}}else if(j==pb){k=i.getAttribute(nb);if(k){try{d=eval(k)}catch(a){alert(qb+k+rb)}}}else if(j==sb){k=i.getAttribute(nb);if(k){try{e=eval(k)}catch(a){alert(qb+k+tb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(ub);if(b==-1){b=a.length}var c=a.indexOf(vb);if(c==-1){c=a.length}var d=a.lastIndexOf(wb,Math.min(c,b));return d>=0?a.substring(0,d+1):Y}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(xb);b.src=a+yb;a=e(b.src)}return a}
function g(){var a=t(zb);if(a!=null){return a}return Y}
function h(){var a=p.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Ab)!=-1){return e(a[b].src)}}return Y}
function i(){var a=p.getElementsByTagName(Bb);if(a.length>0){return a[a.length-1].href}return Y}
function j(){var a=p.location;return a.href==a.protocol+Cb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==Y){k=h()}if(k==Y){k=i()}if(k==Y&&j()){k=e(p.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.__moduleBase+a}
function D(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[Db]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Eb)!=-1}())return Eb;if(function(){return b.indexOf(Fb)!=-1}())return Gb;if(function(){return b.indexOf(Hb)!=-1&&p.documentMode>=9}())return Ib;if(function(){return b.indexOf(Hb)!=-1&&p.documentMode>=8}())return Jb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Kb;if(function(){return b.indexOf(Lb)!=-1}())return Mb;return Nb};i[Db]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};s=function(a,b){return b in i[a]};eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.__computePropValue=k;o.__gwt_activeModules[O].bindings=eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.__getPropMap;r(K,Ob);if(q()){return C(Pb)}var l;try{h([Kb],Qb);h([Mb],Rb);h([Jb],Sb);h([Gb],Tb);h([Eb],Ub);h([Ib],Vb);l=f[k(Db)];var m=l.indexOf(Wb);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.__softPermutationId=g;return C(l+Xb)}
function E(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Yb,L);r(Yb,Zb)}
A();eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.__moduleBase=B();u[O].moduleBase=eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.__moduleBase;var F=D();if(o){o.__gwt_activeModules[O].canRedirect=true}var G=$b;var H=o.sessionStorage[G];if(H&&!o[G]){o[G]=true;var I=p.createElement(db);o[G+_b]=B();I.src=H;var J=p.getElementsByTagName(hb)[0];J.insertBefore(I,J.firstElementChild||J.children[0]);return false}E();r(K,Zb);z(F);return true}
eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet.succeeded=eu_etaxonomy_cdm_remote_webapp_view_widgetset_AppWidgetSet();