//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.17 at 04:06:44 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://rs.tdwg.org/dwc/text/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.etaxonomy.cdm.io.dwca.jaxb;
