// $Id$
/**
* Copyright (C) 2009 EDIT
* European Distributed Institute of Taxonomy 
* http://www.e-taxonomy.eu
* 
* The contents of this file are subject to the Mozilla Public License Version 1.1
* See LICENSE.TXT at the top of this package for the full license terms.
*/
package eu.etaxonomy.cdm.remote.webapp.view.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

/**
 * @author a.oppermann
 * @date 26.04.2013
 *
 */
public class ExportWindow extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Panel exportPanel;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_2;
	@AutoGenerated
	private Button button_2;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private CheckBox checkBox_2;
	@AutoGenerated
	private CheckBox exportCheckBox;
	@AutoGenerated
	private ComboBox comboBox_2;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ExportWindow() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// exportPanel
		exportPanel = buildExportPanel();
		mainLayout.addComponent(exportPanel, "top:0.0px;left:-2.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildExportPanel() {
		// common part: create layout
		exportPanel = new Panel();
		exportPanel.setImmediate(false);
		exportPanel.setWidth("100.0%");
		exportPanel.setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		exportPanel.setContent(verticalLayout_1);
		
		return exportPanel;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
		verticalLayout_1.setMargin(false);
		
		// absoluteLayout_2
		absoluteLayout_2 = buildAbsoluteLayout_2();
		verticalLayout_1.addComponent(absoluteLayout_2);
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_2() {
		// common part: create layout
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth("100.0%");
		absoluteLayout_2.setHeight("100.0%");
		
		// comboBox_2
		comboBox_2 = new ComboBox();
		comboBox_2.setImmediate(false);
		comboBox_2.setWidth("-1px");
		comboBox_2.setHeight("-1px");
		absoluteLayout_2.addComponent(comboBox_2, "top:195.0px;left:241.0px;");
		
		// exportCheckBox
		exportCheckBox = new CheckBox();
		exportCheckBox.setCaption("RedList 1996");
		exportCheckBox.setImmediate(false);
		exportCheckBox.setWidth("-1px");
		exportCheckBox.setHeight("-1px");
		absoluteLayout_2.addComponent(exportCheckBox,
				"top:231.0px;left:241.0px;");
		
		// checkBox_2
		checkBox_2 = new CheckBox();
		checkBox_2.setCaption("CheckBox");
		checkBox_2.setImmediate(false);
		checkBox_2.setWidth("-1px");
		checkBox_2.setHeight("-1px");
		absoluteLayout_2.addComponent(checkBox_2, "top:253.0px;left:241.0px;");
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Button");
		button_1.setImmediate(false);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		absoluteLayout_2.addComponent(button_1, "top:313.0px;left:241.0px;");
		
		// button_2
		button_2 = new Button();
		button_2.setCaption("Button");
		button_2.setImmediate(false);
		button_2.setWidth("-1px");
		button_2.setHeight("-1px");
		absoluteLayout_2.addComponent(button_2, "top:313.0px;left:351.0px;");
		
		return absoluteLayout_2;
	}

}
