/**
* Copyright (C) 2007 EDIT
* European Distributed Institute of Taxonomy 
* http://www.e-taxonomy.eu
* 
* The contents of this file are subject to the Mozilla Public License Version 1.1
* See LICENSE.TXT at the top of this package for the full license terms.
*/

package eu.etaxonomy.cdm.model.taxon;


import org.apache.log4j.Logger;

/**
 * @author Andreas Mueller
 * @version 1.0
 * @created 15-Aug-2007 18:36:02
 */
public enum ConceptRelationshipType {
	TAXONOMICALLY_INCLUDED_IN,
	MISAPPLIED_NAME_FOR,
	INVALID_DESIGNATION_FOR,
	CONTRADICTION,
	CONGRUENT_TO,
	INCLUDED_IN,
	CONGRUENT_TO_OR_INCLUDED_IN,
	INCLUDES,
	CONGRUENT_TO_OR_INCLUDES,
	INCLUDED_IN_OR_INCLUDES,
	CONGRUENT_TO_OR_INCLUDED_IN_OR_INCLUDES,
	OVERLAPS,
	CONGRUENT_TO_OR_OVERLAPS,
	INCLUDED_IN_OR_OVERLAPS,
	CONGRUENT_TO_OR_INCLUDED_IN_OR_OVERLAPS,
	INCLUDES_OR_OVERLAPS,
	CONGRUENT_TO_OR_INCLUDES_OR_OVERLAPS,
	INCLUDED_IN_OR_INCLUDES_OR_OVERLAPS,
	DOES_NOT_EXCLUDE,
	EXCLUDES,
	CONGRUENT_TO_OR_EXCLUDES,
	INCLUDED_IN_OR_EXCLUDES,
	CONGRUENT_TO_OR_INCLUDED_IN_OR_EXCLUDES,
	INCLUDES_OR_EXCLUDES,
	CONGRUENT_TO_OR_INCLUDES_OR_EXCLUDES,
	INCLUDED_IN_OR_INCLUDES_OR_EXCLUDES,
	DOES_NOT_OVERLAP,
	OVERLAPS_OR_EXCLUDES,
	CONGRUENT_TO_OR_OVERLAPS_OR_EXCLUDES,
	INCLUDED_IN_OR_OVERLAPS_OR_EXCLUDES,
	DOES_NOT_INCLUDE,
	INCLUDES_OR_OVERLAPS_OR_EXCLUDES,
	NOT_INCLUDED_IN,
	NOT_CONGRUENT_TO,
	ALL_RELATIONSHIPS
}