//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.21 at 08:13:35 PM GMT 
//


package eu.etaxonomy.cdm.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Namespaces complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Namespaces", namespace="http://etaxonomy.eu/cdm/model/common/1.0", propOrder = {
    "namespace"
})
public class NamespacesElement {

    @XmlElement(name = "Namespace", namespace="http://etaxonomy.eu/cdm/model/common/1.0", required = true)
    protected List<Namespace> namespace = new ArrayList<Namespace>();

    /**
     * Gets the value of the languageString property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languageString property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguageString().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Namespace }
     * 
     * 
     */
    public List<Namespace> getNamespace() {
        return this.namespace;
    }

}
