//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.11.02 at 12:58:05 PM GMT
//


package eu.etaxonomy.cdm.remote.dto.oaipmh;

import java.time.ZonedDateTime;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import eu.etaxonomy.cdm.jaxb.DateTimeAdapter;


/**
 * Define requestType, indicating the protocol request that
 *       led to the response. Element content is BASE-URL, attributes are arguments
 *       of protocol request, attribute-values are values of arguments of protocol
 *       request
 *
 * <p>Java class for requestType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="requestType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
 *       &lt;attribute name="verb" type="{http://www.openarchives.org/OAI/2.0/}verbType" />
 *       &lt;attribute name="identifier" type="{http://www.openarchives.org/OAI/2.0/}identifierType" />
 *       &lt;attribute name="metadataPrefix" type="{http://www.openarchives.org/OAI/2.0/}metadataPrefixType" />
 *       &lt;attribute name="from" type="{http://www.openarchives.org/OAI/2.0/}UTCdatetimeType" />
 *       &lt;attribute name="until" type="{http://www.openarchives.org/OAI/2.0/}UTCdatetimeType" />
 *       &lt;attribute name="set" type="{http://www.openarchives.org/OAI/2.0/}setSpecType" />
 *       &lt;attribute name="resumptionToken" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "requestType", propOrder = {
    "value"
})
public class Request {

    @XmlValue
    @XmlSchemaType(name = "anyURI")
    protected String value;
    @XmlAttribute
    protected Verb verb;
    @XmlAttribute
    protected String identifier;
    @XmlAttribute
    protected MetadataPrefix metadataPrefix;
    @XmlAttribute
    @XmlJavaTypeAdapter(DateTimeAdapter.class)
    protected ZonedDateTime from;
    @XmlAttribute
    @XmlJavaTypeAdapter(DateTimeAdapter.class)
    protected ZonedDateTime until;
    @XmlAttribute
    protected SetSpec set;
    @XmlAttribute
    protected String resumptionToken;

    /**
     * Gets the value of the value property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the verb property.
     *
     * @return
     *     possible object is
     *     {@link Verb }
     *
     */
    public Verb getVerb() {
        return verb;
    }

    /**
     * Sets the value of the verb property.
     *
     * @param value
     *     allowed object is
     *     {@link Verb }
     *
     */
    public void setVerb(Verb value) {
        this.verb = value;
    }

    /**
     * Gets the value of the identifier property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the metadataPrefix property.
     *
     * @return
     *     possible object is
     *     {@link MetadataPrefix }
     *
     */
    public MetadataPrefix getMetadataPrefix() {
        return metadataPrefix;
    }

    /**
     * Sets the value of the metadataPrefix property.
     *
     * @param object
     *     allowed object is
     *     {@link MetadataPrefix }
     *
     */
    public void setMetadataPrefix(MetadataPrefix object) {
        this.metadataPrefix = object;
    }

    /**
     * Gets the value of the from property.
     *
     * @return
     *     possible object is
     *     {@link DateTime }
     *
     */
    public ZonedDateTime getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     *
     * @param dateTime
     *     allowed object is
     *     {@link DateTime }
     *
     */
    public void setFrom(ZonedDateTime dateTime) {
        this.from = dateTime;
    }

    /**
     * Gets the value of the until property.
     *
     * @return
     *     possible object is
     *     {@link DateTime }
     *
     */
    public ZonedDateTime getUntil() {
        return until;
    }

    /**
     * Sets the value of the until property.
     *
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *
     */
    public void setUntil(ZonedDateTime value) {
        this.until = value;
    }

    /**
     * Gets the value of the set property.
     *
     * @return
     *     possible object is
     *     {@link SetSpec }
     *
     */
    public SetSpec getSet() {
        return set;
    }

    /**
     * Sets the value of the set property.
     *
     * @param setSpec
     *     allowed object is
     *     {@link SetSpec }
     *
     */
    public void setSet(SetSpec setSpec) {
        this.set = setSpec;
    }

    /**
     * Gets the value of the resumptionToken property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getResumptionToken() {
        return resumptionToken;
    }

    /**
     * Sets the value of the resumptionToken property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setResumptionToken(String value) {
        this.resumptionToken = value;
    }

}
