<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <artifactId>cdmlib-parent</artifactId>
    <groupId>eu.etaxonomy</groupId>
    <version>6.0.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>cdmlib-remote-webapp</artifactId>
  <name>CDM Remote Webapp</name>
  <packaging>war</packaging>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <!-- by default 
      no further args by now, see profiles for alternative run configurations -->
  </properties>

  <profiles>
    <profile>
      <id>local-repository</id>
      <activation>
        <property>
          <name>localrepo</name>
        </property>
      </activation>
      <repositories>
        <repository>
          <id>EditLocalRepository</id>
          <url>file://${localrepo}/eu/etaxonomy/</url>
          <releases>
            <enabled>false</enabled>
            <updatePolicy>always</updatePolicy>
          </releases>
          <snapshots>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
          </snapshots>
        </repository>
      </repositories>
    </profile>
    <!-- ========================= PROFILE : db-create ========================= -->
    <!--  How to execute from parent project:
        1.) mvn package -DskipTests 
        2.) mvn integration-test -pl cdmlib-remote-webapp -Pdb-create
    -->
    <profile>
      <id>db-create</id>
      <activation>
        <property>
          <name>db-create</name>
        </property>
      </activation>
      <properties>
        <datasource>h2_cdm_blank</datasource>
        <forceSchemaCreate>true</forceSchemaCreate>
        <log4jFile>${project.build.directory}/target/test-classes/log4j2.xml</log4jFile>
        <beanDefinitionFile>${project.build.directory}/test-classes/datasources.xml</beanDefinitionFile>
        <spring.profiles>swagger</spring.profiles>
      </properties>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>2.22.2</version>
            <configuration>
              <forkCount>3</forkCount>
              <reuseForks>true</reuseForks>
            </configuration>
            <executions>
              <execution>
                <goals>
                  <goal>integration-test</goal>
                  <goal>verify</goal>
                </goals>
                <configuration>
                  <includes>
                    <include>**/ForceSchemaCreateIT.java</include>
                  </includes>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
    <!-- ========================= DEFAULT-PROFILE : db-use ========================= -->
     <profile>
      <id>db-use</id>
      <activation>
        <activeByDefault>true</activeByDefault>
        <property>
          <name>db-use</name>
        </property>
      </activation>
      <properties>
        <datasource>h2_cdmTest</datasource>
        <forceSchemaCreate>false</forceSchemaCreate>
        <integrationTest.log4j.configuration>${project.build.directory}/target/test-classes/log4j2.xml</integrationTest.log4j.configuration>
        <beanDefinitionFile>${project.build.directory}/test-classes/datasources.xml</beanDefinitionFile>
        <spring.profiles>swagger</spring.profiles>
      </properties>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>2.22.2</version>
            <configuration>
              <forkCount>3</forkCount>
              <reuseForks>true</reuseForks>
            </configuration>
            <executions>
              <execution>
                <goals>
                  <goal>integration-test</goal>
                  <goal>verify</goal>
                </goals>
                <configuration>
                  <systemPropertyVariables>
                    <cdm.datasource>h2_cdmTest</cdm.datasource>
                  </systemPropertyVariables>
                  <excludes>
                    <exclude>**/ForceSchemaCreateIT.java</exclude>
                  </excludes>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
  <dependencies>
    <dependency>
      <groupId>eu.etaxonomy</groupId>
      <artifactId>cdmlib-remote</artifactId>
      <exclusions>
        <!-- exclude all jdbc drivers from the war. Jdbc drivers must only 
          be added to {APPLICATION_CONTAINER}/lib see https://dev.e-taxonomy.eu/redmine/issues/4955 
          and https://stackoverflow.com/questions/6981564/why-must-the-jdbc-driver-be-put-in-tomcat-home-lib-folder -->
        <exclusion>
          <groupId>eu.etaxonomy</groupId>
          <artifactId>cdmlib-db</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>eu.etaxonomy</groupId>
      <artifactId>cdmlib-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <!-- TODO this is also offered by cdmlib-remote, can it be removed? 
        What does provided mean? -->
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>xmlunit</groupId>
      <artifactId>xmlunit</artifactId>
    </dependency>
    <!-- JsonView -->
    <!-- -->
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-oxm</artifactId>
    </dependency>

    <!-- XmlView -->
    <dependency>
      <!-- this is also offered by cdmlib-remote. Can it be removed? -->
      <groupId>com.thoughtworks.xstream</groupId>
      <artifactId>xstream</artifactId>
      <exclusions>
        <!-- https://stackoverflow.com/questions/17077922/maven-xpp3-versus-xpp3-min -->
        <!-- But maybe we can exclude xpp3 instead, not sure if it is directly needed or only for xstream -->
        <exclusion>
            <groupId>xpp3</groupId>
            <artifactId>xpp3_min</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <!-- swagger -->
    <dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-swagger2</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- dependencies for springfox-swagger2, added explicitly to pin the 
      version these dependencies are also required by the cdmlib! -->
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
    </dependency>
    <!-- needed here? It is already mentioned in cdmlib-model -->
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
    </dependency>
    <!-- END of dependencies for swagger-springmvc, added explicitely -->

    <!-- testing -->
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>

    <!-- Connection Pooling and jdbc -->
    <dependency>
      <groupId>org.hibernate</groupId>
      <artifactId>hibernate-c3p0</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- <dependency> -->
    <!-- <groupId>com.mchange</groupId> -->
    <!-- <artifactId>c3p0</artifactId> -->
    <!-- <scope>test</scope> -->
    <!-- </dependency> -->
    <!-- Profiling -->
    <dependency>
      <groupId>com.yourkit</groupId>
      <artifactId>yjp-controller-api-redist</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <resources>
      <resource>
        <!-- replace the place holders like ${...} in datasources.xml -->
        <filtering>true</filtering>
        <directory>src/test/resources</directory>
        <targetPath>../test-classes</targetPath>
        <includes>
          <include>datasources.xml</include>
        </includes>
      </resource>
      <resource>
        <!-- all other test resources without filtering -->
        <directory>src/test/resources</directory>
        <targetPath>../test-classes</targetPath>
        <excludes>
          <exclude>datasources.xml</exclude>
        </excludes>
      </resource>
      <resource>
        <!-- all main resources without filtering -->
        <directory>src/main/resources</directory>
      </resource>
    </resources>
    
    <!-- PLUGINS -->
    <plugins>
      <plugin>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-maven-plugin</artifactId>
        <version>10.0.26</version>
        <configuration>
          <stopKey>stop</stopKey>
          <stopPort>9199</stopPort>
          <scan>10</scan>
          <useTestScope>true</useTestScope>
          <!-- jvmArgs will only be used when running mvn jetty:run-forked (<deployMode>FORK</deployMode> in jetty 10+) -->
          <jvmArgs>-Xmx2000M 
            -Dcdm.datasource=${datasource}
            -Duser.home=${basedir}/target/target/
            -Dcdm.beanDefinitionFile=${project.build.directory}/test-classes/datasources.xml
            -Dspring.profiles.active=remoting
            -Dcdm.forceSchemaCreate=${forceSchemaCreate}
            -Dlog4j.configuration=${log4jFile}
            -Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
            --add-opens java.base/java.lang=ALL-UNNAMED
          </jvmArgs>
<!--          <jettyXml>${basedir}/src/test/resources/etc/jetty/jetty.xml,${basedir}/src/test/resources/etc/jetty/jetty-http.xml</jettyXml>-->
          <jettyXmls>
            <jettyXml>${basedir}/src/test/resources/etc/jetty/jetty.xml</jettyXml>
            <jettyXml>${basedir}/src/test/resources/etc/jetty/jetty-http.xml</jettyXml>
<!--            <jettyXml>${basedir}/src/test/resources/etc/jetty/jetty-ssl.xml</jettyXml>-->
<!--            <jettyXml>${basedir}/src/test/resources/etc/jetty/jetty-https.xml</jettyXml>-->
          </jettyXmls>
          
          <systemProperties>
              <cdm.datasource>${datasource}</cdm.datasource>
              <!-- The lucene index should be placed into the target folder, 
                so user.home needs to be set to this folder. user.home needs to be overridden 
                since it already exists, thus the force option is turned on above -->
              <user.home>${basedir}/target/</user.home>
              <!-- datasources.xml is prepared by <plugins><resources>..</resources> above -->
              <cdm.beanDefinitionFile>${beanDefinitionFile}</cdm.beanDefinitionFile>
              <cdm.forceSchemaCreate>${forceSchemaCreate}</cdm.forceSchemaCreate>
              <!-- start with swagger profile so that the swagger doc can 
                be generated -->
              <spring.profiles.active>${spring.profiles}</spring.profiles.active>
              <log4j.configuration>${log4jFile}</log4j.configuration>
          </systemProperties>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>${h2.version}</version>
          </dependency>
          <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>${mysql.version}</version>
          </dependency>
          <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>${mariadb.version}</version>
          </dependency>
<!--          <dependency>-->
<!--            <groupId>com.mchange</groupId>-->
<!--            <artifactId>c3p0</artifactId>-->
<!--            <version>${c3p0.version}</version>-->
<!--          </dependency>-->
        </dependencies>
        <executions>
          <execution>
            <id>start-jetty</id>
            <phase>pre-integration-test</phase>
            <goals>
              <goal>start</goal>
            </goals>
            <configuration>
              <scanIntervalSeconds>0</scanIntervalSeconds>
            </configuration>
          </execution>
          <execution>
            <id>stop-jetty</id>
            <phase>post-integration-test</phase>
            <goals>
              <goal>stop</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.3.2</version>   
        <configuration>
          <packagingExcludes>WEB-INF/lib/spring-web-*.jar</packagingExcludes>
        </configuration>    
        <executions>
          <execution>
            <!-- The war must be created after running the integration-tests, 
              since the SwaggerGroupsIT test populates the classes/api-docs-static/ folder 
              with static swagger doc files. They are otherwise not packed into the war 
              file. -->
            <phase>verify</phase>
            <goals>
              <goal>war</goal>
            </goals>           
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.2.0</version>
        <configuration>
          <escapeWindowsPaths>false</escapeWindowsPaths>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
